
module VGA (
    input wire clk_25m,
    input wire clk_100m,
    input wire rst,
    
    input wire [31:0] PC_IF,
    input wire [31:0] inst_IF,
    input wire [31:0] PC_ID,
    input wire [31:0] inst_ID,
    input wire [31:0] PC_Ex,
    input wire MemRW_Ex,
    input wire MemRW_Mem,
    input wire [31:0] Data_out,
    input wire [31:0] Addr_out,
    input wire [31:0] Data_out_WB,
    output wire hs,
    output wire vs,
    output wire [3:0] vga_r,
    output wire [3:0] vga_g,
    output wire [3:0] vga_b,
    
    //self-define
     input [31:0]reg_val_1,
    input [31:0]reg_val_2,
    input [31:0]reg_val_3,
    input [31:0]reg_val_4,
    input [31:0]reg_val_5,
    input [31:0]reg_val_6,
    input [31:0]reg_val_7,
    input [31:0]reg_val_8,
    input [31:0]reg_val_9,
    input [31:0]reg_val_10,
    input [31:0]reg_val_11,
    input [31:0]reg_val_12,
    input [31:0]reg_val_13,
    input [31:0]reg_val_14,
    input [31:0]reg_val_15,
    input [31:0]reg_val_16,
    input [31:0]reg_val_17,
    input [31:0]reg_val_18,
    input [31:0]reg_val_19,
    input [31:0]reg_val_20,
    input [31:0]reg_val_21,
    input [31:0]reg_val_22,
    input [31:0]reg_val_23,
    input [31:0]reg_val_24,
    input [31:0]reg_val_25,
    input [31:0]reg_val_26,
    input [31:0]reg_val_27,
    input [31:0]reg_val_28,
    input [31:0]reg_val_29,
    input [31:0]reg_val_30,
    input [31:0]reg_val_31,
    input [31:0]IdEx_inst,
    input IdEx_valid,
    input [4:0]IdEx_rd,
    input [4:0]IdEx_rs1,
    input [4:0]IdEx_rs2,
    input [31:0]IdEx_rs1_val,
    input [31:0]IdEx_rs2_val,
    input IdEx_reg_wen,
    input IdEx_is_imm,
    input [31:0]IdEx_imm,
    input IdEx_mem_ren,
    input IdEx_is_branch,
    input IdEx_is_jal,
    input IdEx_is_jalr,
    input IdEx_is_auipc,
    input IdEx_is_lui,
    input [3:0]IdEx_alu_ctrl,
    input IdEx_cmp_ctrl,
    input [31:0]ExMa_pc,
    input [31:0]ExMa_inst,
    input ExMa_valid,
    input [4:0]ExMa_rd,
    input ExMa_reg_wen,
    input [4:0]MEMWB_rd,
    input MEMWB_reg_wen,
    input [31:0]MEMWB_pc,
    input [31:0]MEMWB_inst
);


    wire [9:0] vga_x;
    wire [8:0] vga_y;
    wire video_on;
    VgaController vga_controller(
        .clk(clk_25m),
        .rst(rst),
        .vga_x(vga_x),
        .vga_y(vga_y),
        .hs(hs),
        .vs(vs),
        .video_on(video_on)
    );

    wire display_wen;
    wire [11:0] display_w_addr;
    wire [7:0] display_w_data;
    VgaDisplay vga_display(
        .clk(clk_100m),
        .video_on(video_on),
        .vga_x(vga_x),
        .vga_y(vga_y),
        .vga_r(vga_r),
        .vga_g(vga_g),
        .vga_b(vga_b),
        .wen(display_wen),
        .w_addr(display_w_addr),
        .w_data(display_w_data)
    );
    

    VgaDebugger vga_debugger(
        // DEBUG
        .pc(PC_IF),
        .inst(inst_IF),
        .IfId_pc(PC_ID),
        .IfId_inst(inst_ID),
        .IfId_valid(),
        .IdEx_pc(PC_Ex),
        .IdEx_inst(IdEx_inst),
        .IdEx_valid(),
        .IdEx_rd(IdEx_rd),
        .IdEx_rs1(IdEx_rs1),
        .IdEx_rs2(IdEx_rs2),
        .IdEx_rs1_val(IdEx_rs1_val),
        .IdEx_rs2_val(IdEx_rs2_val),
        .IdEx_reg_wen(IdEx_reg_wen),
        .IdEx_is_imm(),
        .IdEx_imm(IdEx_imm),
        .IdEx_mem_wen(MemRW_Ex),
        .IdEx_mem_ren(),
        .IdEx_is_branch(IdEx_is_branch),
        .IdEx_is_jal(IdEx_is_jal),
        .IdEx_is_jalr(),
        .IdEx_is_auipc(),
        .IdEx_is_lui(),
        .IdEx_alu_ctrl(IdEx_alu_ctrl),
        .IdEx_cmp_ctrl(),
        .ExMa_pc(ExMa_pc),
        .ExMa_inst(ExMa_inst),
        .ExMa_valid(),
        .ExMa_rd(ExMa_rd),
        .ExMa_reg_wen(ExMa_reg_wen),
        .ExMa_mem_w_data(Data_out),
        .ExMa_alu_res(Addr_out),
        .ExMa_mem_wen(MemRW_Mem),
        .ExMa_mem_ren(),
        .ExMa_is_jal(),
        .ExMa_is_jalr(),
        .MaWb_pc(MEMWB_pc),
        .MaWb_inst(MEMWB_inst),
        .MaWb_valid(),
        .MaWb_rd(MEMWB_rd),
        .MaWb_reg_wen(MEMWB_reg_wen),
        .MaWb_reg_w_data(Data_out_WB),
        .x0(),
        .ra            (reg_val_1               ),
         .sp            (reg_val_2               ),
         .gp            (reg_val_3               ),
         .tp            (reg_val_4               ),
         .t0            (reg_val_5               ),
         .t1            (reg_val_6               ),
         .t2            (reg_val_7               ),
         .s0            (reg_val_8               ),
         .s1            (reg_val_9               ),
         .a0            (reg_val_10               ),
         .a1            (reg_val_11               ),
         .a2            (reg_val_12               ),
         .a3            (reg_val_13               ),
         .a4            (reg_val_14               ),
         .a5            (reg_val_15               ),
         .a6            (reg_val_16               ),
         .a7            (reg_val_17              ),
         .s2            (reg_val_18               ),
         .s3            (reg_val_19               ),
         .s4            (reg_val_20               ),
         .s5            (reg_val_21               ),
         .s6            (reg_val_22               ),
         .s7            (reg_val_23               ),
         .s8            (reg_val_24               ),
         .s9            (reg_val_25               ),
         .s10           (reg_val_26               ),
         .s11           (reg_val_27               ),
         .t3            (reg_val_28               ),
         .t4            (reg_val_29               ),
         .t5            (reg_val_30               ),
         .t6            (reg_val_31               ),
        .clk(clk_100m),
        .display_wen(display_wen),
        .display_w_addr(display_w_addr),
        .display_w_data(display_w_data)
    );


    
endmodule