# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/VivadoProject/asd/pipline_cpu.cache/wt [current_project]
set_property parent.project_path D:/VivadoProject/asd/pipline_cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/VivadoProject/asd/pipline_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/I_int.coe
add_files D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/IP_edf/P.coe
add_files D:/OExp05-Pipeline_CPU/h.coe
add_files D:/OExp05-Pipeline_CPU/P.coe
add_files D:/VivadoProject/h.coe
add_files -quiet D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SSeg7_Dev/SSeg7_Dev.runs/synth_1/SSeg7_Dev.dcp
set_property used_in_implementation false [get_files D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SSeg7_Dev/SSeg7_Dev.runs/synth_1/SSeg7_Dev.dcp]
add_files -quiet D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/VGA/VGA.runs/synth_2/VGA.dcp
set_property used_in_implementation false [get_files D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/VGA/VGA.runs/synth_2/VGA.dcp]
read_mem {
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.ip_user_files/sim_scripts/ROM_D/riviera/ROM_D.mif
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.ip_user_files/sim_scripts/ROM_D/vcs/ROM_D.mif
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.ip_user_files/sim_scripts/ROM_D/ies/ROM_D.mif
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.ip_user_files/sim_scripts/ROM_D/xcelium/ROM_D.mif
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.ip_user_files/sim_scripts/ROM_D/activehdl/ROM_D.mif
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.ip_user_files/mem_init_files/ROM_D.mif
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.ip_user_files/sim_scripts/ROM_D/questa/ROM_D.mif
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.sim/sim_1/behav/xsim/ROM_D.mif
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.ip_user_files/sim_scripts/ROM_D/modelsim/ROM_D.mif
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/CPU_interpert.ip_user_files/sim_scripts/ROM_D/xsim/ROM_D.mif
}
read_verilog -library xil_defaultlib {
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/IP_base/ALU.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/Counter_x.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/SSeg7_Dev/SSeg7_Dev.srcs/sources_1/new/HexTo8SEG.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/new/IP2CPU_pipcpu.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/ImmGen.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/SSeg7_Dev/SSeg7_Dev.srcs/sources_1/new/MC14495_ZJU.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/MIO_BUS.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/IP_base/MUX/MUX2T1_64/MUX2T1_64.srcs/sources_1/imports/MUX_W/MUX2T1_64.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/Multi_8CH32.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/SSeg7_Dev/SSeg7_Dev.srcs/sources_1/new/P2S.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/PC.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/RAM_B.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/RegFile.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/SAnti_jitter.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/Single_CPU_base/SCPU_4921.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/SPIO.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/SSeg7_Dev/SSeg7_Dev.srcs/sources_1/new/SSeg7_Dev.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/SSeg7_Dev/SSeg7_Dev.srcs/sources_1/new/SSeg_map.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/Framework/VGA.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/Framework/VgaController.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/Framework/VgaDebugger.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/Framework/VgaDisplay.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/clk_div.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/new/my_Ex_reg_Mem.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/new/my_ID_reg_EX.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/new/my_IF_reg_ID.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/new/my_Mem_reg_WB.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/new/my_PIP_ID.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/new/my_PIP_IF.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/new/my_pip_Ex.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/new/my_pip_WB.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/new/my_pipline_Mem.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/pipline_cpu/stall.v
  D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/Single_CPU_base/soc.v
}
read_ip -quiet D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/ip/ROM_D/ROM_D.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/asd/pipline_cpu.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc]

read_edif D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/IP_base/MUX/MUX2T1_64/MUX2T1_64.srcs/sources_1/imports/MUX_W/MUX2T1_64.edf
read_edif D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/SPIO.edf
read_edif D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/Multi_8CH32.edf
read_edif D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/MIO_BUS.edf
read_edif D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/RAM_B.edf
read_edif D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/Counter_x.edf
read_edif D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/clk_div.edf
read_edif D:/VivadoProject/asd/pipline_cpu.srcs/sources_1/imports/CPU_interpert/IP/CPU_implement/Supplementary/SAnti_jitter.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/VivadoProject/asd/pipline_cpu.srcs/constrs_1/imports/OExp02-IP2SOC/Org-Sword.xdc
set_property used_in_implementation false [get_files D:/VivadoProject/asd/pipline_cpu.srcs/constrs_1/imports/OExp02-IP2SOC/Org-Sword.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc -part xc7k160tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_utilization_synth.rpt -pb soc_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
