# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/OExp02-IP2SOC/Org-Sword.xdc

# IP: ip/ROM_D/ROM_D.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_D || ORIG_REF_NAME==ROM_D} -quiet] -quiet

# XDC: ip/ROM_D/ROM_D_ooc.xdc
