# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/VivadoProject/CPU_interpert/CPU_interpert.cache/wt [current_project]
set_property parent.project_path D:/VivadoProject/CPU_interpert/CPU_interpert.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/VivadoProject/CPU_interpert/CPU_interpert.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/VivadoProject/New-Single_cpu_1/OExp02-IP2SOC/temp.coe
add_files d:/VivadoProject/CPU_interpert/I_int.coe
add_files -quiet D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SSeg7_Dev/SSeg7_Dev.runs/synth_1/SSeg7_Dev.dcp
set_property used_in_implementation false [get_files D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SSeg7_Dev/SSeg7_Dev.runs/synth_1/SSeg7_Dev.dcp]
add_files -quiet D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/VGA/VGA.runs/synth_2/VGA.dcp
set_property used_in_implementation false [get_files D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/VGA/VGA.runs/synth_2/VGA.dcp]
read_verilog -library xil_defaultlib {
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/VivadoProject/CPU_interpert/IP/IP_base/ALU.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/Counter_x.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Single_CPU_base/DataPath_2022.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/VGA/VGA.srcs/sources_1/new/Hex2Ascii.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SSeg7_Dev/SSeg7_Dev.srcs/sources_1/new/HexTo8SEG.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Single_CPU_base/IP2CPU.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Single_CPU_base/ImmGen.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SSeg7_Dev/SSeg7_Dev.srcs/sources_1/new/MC14495_ZJU.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/MIO_BUS.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SSeg7_Dev/SSeg7_Dev.srcs/sources_1/new/MUX2T1_64.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/Multi_8CH32.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SSeg7_Dev/SSeg7_Dev.srcs/sources_1/new/P2S.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Single_CPU_base/PC.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/RAM_B.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Single_CPU_base/RegFile.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SAnti_jitter.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Single_CPU_base/SCPU_4921.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SPIO.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SSeg7_Dev/SSeg7_Dev.srcs/sources_1/new/SSeg7_Dev.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SSeg7_Dev/SSeg7_Dev.srcs/sources_1/new/SSeg_map.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/VGA/VGA.srcs/sources_1/new/VGA.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/VGA/VGA.srcs/sources_1/new/VgaController.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/VGA/VGA.srcs/sources_1/new/VgaDebugger.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/VGA/VGA.srcs/sources_1/new/VgaDisplay.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/clk_div.v
  D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Single_CPU_base/soc.v
}
read_ip -quiet D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/ip/ROM_D/ROM_D.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc]

read_edif D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SPIO.edf
read_edif D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/Multi_8CH32.edf
read_edif D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/MIO_BUS.edf
read_edif D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/RAM_B.edf
read_edif D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/Counter_x.edf
read_edif D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/clk_div.edf
read_edif D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/sources_1/imports/Supplementary/SAnti_jitter.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/constrs_1/imports/OExp02-IP2SOC/Org-Sword.xdc
set_property used_in_implementation false [get_files D:/VivadoProject/CPU_interpert/CPU_interpert.srcs/constrs_1/imports/OExp02-IP2SOC/Org-Sword.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc -part xc7k160tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_utilization_synth.rpt -pb soc_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
